# Generated by Django 4.2.2 on 2023-06-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250, null=True)),
                ('file_type', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio'), ('Image', 'Image')], max_length=250, null=True)),
                ('file_url', models.CharField(max_length=800, null=True)),
            ],
        ),
    ]
